# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: "Execução Manual"

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  testes-unidade:
    # maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalação das dependências
      - name: Instalando dependências
        run: npm install

      - name: Verificar arquivos
        run: |
          echo "Verificando se o arquivo existe:"
          ls -la Conceitos/testes-de-unidade.js || echo "Arquivo não encontrado"

      # instalação do Mocha
      - name: Instalando Mocha
        run: npm install -D mocha

      # executar os testes e2e
      - name: Executando Testes
        run: npx mocha testes/01-testes.js
